
import { parser } from './pascal_parser.js';

/**
 * PascalASTInterpreter
 * Interprets the AST generated by pascal_parser.cjs
 */
export class PascalASTInterpreter {
    constructor() {
        this.variables = {};
        this.variableTypes = {}; // Store declared types for validation
        this.outputCallback = null;
        this.inputCallback = null;
        this.isRunning = false;
        this.stepCount = 0;

        // Trace Mode State
        this.traceMode = false;
        this.traceSteps = [];
        this.currentLogs = [];
        this.lastLineRecorded = -1;
    }

    /**
     * Run the code interactively.
     * @param {string} code - The Pascal source code
     * @param {function} onOutput - Callback(text) for output
     * @param {function} onInput - Async Callback() returning string/number for input
     */
    async runInteractive(code, onOutput, onInput) {
        this.variables = {}; // Reset variables
        this.stepCount = 0;
        this.outputCallback = onOutput;
        this.inputCallback = onInput;
        this.isRunning = true;
        this.traceMode = false;

        try {
            // We imported { parser } directly.
            const p = parser;

            const ast = p.parse(code);
            await this.visit(ast);
        } catch (e) {
            this.logOutput(`[ERROR]: ${e.message}\n`);
            console.error(e);
        } finally {
            this.isRunning = false;
        }
    }

    /**
     * Run the code in Trace Mode (for Block Game validation).
     * @param {string} code - The Pascal source code
     * @param {object} inputContext - Map of variables or numeric inputs
     * @returns {Promise<Array>} - The array of steps
     */
    async runTrace(code, inputContext = {}) {
        this.variables = {};
        for (const k in inputContext) {
            this.variables[k.toLowerCase()] = inputContext[k];
        }
        this.stepCount = 0;
        this.traceMode = true;
        this.traceSteps = [];
        this.currentLogs = [];
        this.lastLineRecorded = -1;
        this.isRunning = true;

        // Mock Output: Collect logs
        this.outputCallback = (text) => {
            // Split by newlines to match Game's expected "logs" array format
            // But Game expects array of strings (lines).
            // "Hello\n" -> ["Hello", ""]
            // The interpreter emits "Hello" then "\n" sometimes.

            // We accumulate in currentLogs. 
            // Logic: append to last log if no newline.
            if (this.currentLogs.length === 0) this.currentLogs.push("");

            const parts = text.split('\n');
            if (parts.length === 1) {
                this.currentLogs[this.currentLogs.length - 1] += parts[0];
            } else {
                this.currentLogs[this.currentLogs.length - 1] += parts[0];
                for (let i = 1; i < parts.length; i++) {
                    this.currentLogs.push(parts[i]);
                }
            }
        };

        // Mock Input: Not supported in trace yet? 
        // Or supported via inputContext?
        // Game sends inputs in context usually.
        this.inputCallback = async () => 0;

        try {
            const ast = parser.parse(code);
            await this.visit(ast);

            // Add a final step for the "end." line (or just end of execution)
            // ensuring the last log output is visible.
            const lines = code.split('\n');
            const lastLineIndex = lines.length - 1;

            // Avoid duplicate if last statement was effectively the last line
            if (this.lastLineRecorded !== lastLineIndex) {
                // Manually push the final state
                const currentVars = {};
                for (const k in this.variables) {
                    if (Object.prototype.hasOwnProperty.call(this.variables, k)) {
                        currentVars[k] = this.variables[k];
                    }
                }
                this.traceSteps.push({
                    lineIndex: lastLineIndex,
                    text: "",
                    logs: [...this.currentLogs],
                    variables: currentVars
                });
            }

        } catch (e) {
            this.currentLogs.push(`[ERROR]: ${e.message}`);
            this.recordError(e);
        } finally {
            this.isRunning = false;
            this.traceMode = false;
        }

        return this.traceSteps;
    }

    logOutput(text) {
        if (this.outputCallback) {
            this.outputCallback(text);
        }
    }

    async requestInput() {
        if (this.inputCallback) {
            return await this.inputCallback();
        }
        return 0;
    }

    /**
     * Preprocess Pascal code to support legacy syntax quirks or formatting.
     * Transforms `write(x:w:p)` -> `write(__fmt(x, w, p))`
     */
    preprocessCode(code) {
        // Simple scanner to identify write/writeln calls and transform args
        return code.replace(/\b(write|writeln)\s*\(([^)]+)\)/gi, (match, func, args) => {
            // Split args by comma, ignoring commas in quotes
            const params = [];
            let currentParam = "";
            let inQuote = false;

            for (let i = 0; i < args.length; i++) {
                const char = args[i];
                if (char === "'") inQuote = !inQuote;
                if (char === "," && !inQuote) {
                    params.push(currentParam);
                    currentParam = "";
                } else {
                    currentParam += char;
                }
            }
            params.push(currentParam);

            // Process parameters
            const processedParams = params.map(p => {
                // Check for colon outside of quotes
                // p: "avg : 0 : 2" or "x:5"
                let tokens = [];
                let currentToken = "";
                let pInQuote = false;

                for (let i = 0; i < p.length; i++) {
                    const char = p[i];
                    if (char === "'") pInQuote = !pInQuote;
                    if (char === ":" && !pInQuote) {
                        tokens.push(currentToken);
                        currentToken = "";
                    } else {
                        currentToken += char;
                    }
                }
                tokens.push(currentToken);

                if (tokens.length > 1) {
                    // It has formatting!
                    // x, w, p
                    const expr = tokens[0].trim();
                    const w = tokens[1].trim();
                    const prec = tokens.length > 2 ? tokens[2].trim() : null;

                    if (prec) {
                        return `__fmt(${expr}, ${w}, ${prec})`;
                    } else {
                        return `__fmt(${expr}, ${w})`;
                    }
                }
                return p;
            });

            return `${func}(${processedParams.join(', ')})`;
        });
    }

    // --- AST TRAVERSAL ---

    async visit(node) {
        if (!node) return;

        // Ensure we stop if requested (implementation detail: usually via flag)
        if (!this.isRunning) return;

        // Trace Recording
        if (this.traceMode && node.lineno !== undefined) {
            // Only record if line changed or it's a significant step?
            // Game highlights blocks. One block per line usually.
            // Repeat visits to same line (loop) should be recorded.
            // We record every visit to a node with a line number.
            this.recordTrace(node);
        }

        // Yield control every few steps to keep UI responsive (ONLY if interactive)
        if (!this.traceMode) {
            this.stepCount++;
            if (this.stepCount > 100) {
                this.stepCount = 0;
                await new Promise(resolve => setTimeout(resolve, 0));
            }
        }

        switch (node.node) {
            case 'program':
                await this.visit(node.block);
                break;
            case 'block':
                // Handle declarations if needed (init variables to 0)
                await this.visitDeclarations(node.decls);
                await this.visitStatements(node.stmts);
                break;

            // STATEMENTS
            case 'stmt_compound':
                await this.visitStatements(node.stmts);
                break;
            case 'stmt_assign':
                await this.executeAssign(node);
                break;
            case 'stmt_call':
                await this.executeCall(node);
                break;
            case 'stmt_if':
                await this.executeIf(node);
                break;
            case 'stmt_while':
                await this.executeWhile(node);
                break;
            case 'stmt_repeat':
                await this.executeRepeat(node);
                break;
            case 'stmt_for':
                await this.executeFor(node);
                break;
            case 'stmt_case':
                await this.executeCase(node);
                break;

            // Empty statements or others
            default:
                // console.warn("Unknown node type:", node.node, node);
                break;
        }
    }

    async visitDeclarations(decls) {
        if (!decls) return;
        for (const decl of decls) {
            if (decl.node === 'var_decl') {
                // Initialize variable to 0 or empty string based on type
                // decl.type.name ('INTEGER', 'STRING', etc.)
                const name = decl.id.toLowerCase(); // Case-insensitive vars
                this.variables[name] = 0;  // Default value

                // Store declared type
                if (decl.type && decl.type.name) {
                    this.variableTypes[name] = decl.type.name.toUpperCase();
                    if (decl.type.name.toUpperCase() === 'STRING') {
                        this.variables[name] = "";
                    }
                }
            } else if (decl.node === 'const_decl') {
                // CONST pi = 3.14;
                const name = decl.id.toLowerCase();
                // node.expr holds the value node, e.g., { node: 'real', val: 3.14 }
                // We need to evaluate it? Or usually it's a literal/constant expression.
                // Let's assume simplest case: evaluate it.
                const val = await this.evaluate(decl.expr);
                this.variables[name] = val;
                // Constants typically don't change type, but we could infer/store it if needed.
                this.variableTypes[name] = 'CONSTANT';
            }
        }
    }

    async visitStatements(stmts) {
        if (!stmts) return;
        for (const stmt of stmts) {
            await this.visit(stmt);
        }
    }

    async executeAssign(node) {
        const varName = node.lvalue.id || node.lvalue; // lvalue can be object or string in some parsers? Check AST.
        // In AST dump: lvalue was { node: 'variable', id: 'X' }
        const target = (node.lvalue.node === 'variable' ? node.lvalue.id : node.lvalue).toLowerCase();

        const val = await this.evaluate(node.expr);
        this.variables[target] = val;
    }

    async executeCall(node) {
        const id = node.id.toUpperCase();
        if (id === 'WRITELN' || id === 'WRITE') {
            let output = "";
            if (node.call_params) {
                for (const param of node.call_params) {
                    output += await this.evaluate(param);
                }
            }
            if (id === 'WRITELN') output += "\n";
            this.logOutput(output);
        } else if (id === 'READLN' || id === 'READ') {
            // Param should be variable
            if (node.call_params && node.call_params.length > 0) {
                const targetNode = node.call_params[0];
                if (targetNode.node === 'variable') {
                    const varName = targetNode.id.toLowerCase();
                    const declaredType = this.variableTypes[varName] || 'UNKNOWN';

                    let inputVal = await this.requestInput();

                    // Validate Type
                    if (declaredType === 'INTEGER') {
                        // Check if numeric and integer
                        if (!/^-?\d+$/.test(String(inputVal).trim())) {
                            throw new Error(`Invalid input for INTEGER variable '${targetNode.id}'. Expected a whole number, got '${inputVal}'.`);
                        }
                        inputVal = parseInt(inputVal, 10);
                    } else if (declaredType === 'REAL') {
                        if (isNaN(parseFloat(inputVal))) {
                            throw new Error(`Invalid input for REAL variable '${targetNode.id}'. Expected a number, got '${inputVal}'.`);
                        }
                        inputVal = parseFloat(inputVal);
                    }

                    this.variables[varName] = inputVal;
                    // Echo output if needed? 
                    // Usually console echoes input. IDE might handle it, but for consistency:
                    this.logOutput(`${inputVal}\n`);
                }
            } else {
                // Just wait for enter
                await this.requestInput();
            }
        } else {
            // Unknown procedure? Or custom one?
            // For now, ignore.
        }
    }

    async executeIf(node) {
        const condition = await this.evaluate(node.expr);
        if (condition) {
            await this.visit(node.tstmt);
        } else if (node.fstmt) {
            await this.visit(node.fstmt);
        }
    }

    async executeWhile(node) {
        // Warning: Infinite Loop Protection needed?
        let steps = 0;
        while (await this.evaluate(node.expr)) {
            await this.visit(node.stmt);
            steps++;
            if (steps > 50000) throw new Error("Infinite Loop Execution Limit Exceeded");
        }
    }

    async executeRepeat(node) {
        let steps = 0;
        do {
            await this.visitStatements(node.stmts);
            steps++;
            if (steps > 50000) throw new Error("Infinite Loop Execution Limit Exceeded");
        } while (!(await this.evaluate(node.expr))); // UNTIL condition is true, loop stops. so loop WHILE NOT expr?
        // Wait, AST says "stmt_repeat". UNTIL implies loop UNTIL true.
        // So loop while False.
    }

    async executeFor(node) {
        const varName = (node.index.id || node.index).toLowerCase();
        const start = await this.evaluate(node.start);
        const end = await this.evaluate(node.end);
        const step = node.by || 1; // 1 for TO, -1 for DOWNTO

        this.variables[varName] = start;
        let running = true;
        let steps = 0;

        while (running) {
            const current = this.variables[varName];

            // Check termination
            if (step > 0 && current > end) break;
            if (step < 0 && current < end) break;

            await this.visit(node.stmt);

            this.variables[varName] += step;
            steps++;
            if (steps > 50000) throw new Error("Infinite Loop Execution Limit Exceeded");
        }
    }


    async executeCase(node) {
        const exprVal = await this.evaluate(node.expr);
        let matchFound = false;

        if (node.cases) {
            for (const caseBranch of node.cases) {
                for (const indexNode of caseBranch.indexes) {
                    const indexVal = await this.evaluate(indexNode);

                    if (indexVal == exprVal) {
                        await this.visit(caseBranch.stmt);
                        matchFound = true;
                        break;
                    }
                }
                if (matchFound) break;
            }
        }

        if (!matchFound && node.otherwise_stmt) {
            if (Array.isArray(node.otherwise_stmt)) {
                await this.visitStatements(node.otherwise_stmt);
            } else {
                await this.visit(node.otherwise_stmt);
            }
        }
    }

    // --- EXPRESSION EVALUATION ---

    async evaluate(node) {
        if (!node) return null;

        switch (node.node) {
            case 'integer':
            case 'real':
            case 'boolean': // if supported
            case 'constant': // Added support for constants (e.g. in case labels)
                return node.val;
            case 'string':
                return node.val;
            case 'variable':
                return this.variables[node.id.toLowerCase()] ?? 0;

            case 'expr_call':
                // Function call in expression
                const funcName = node.id.toUpperCase();
                const args = [];
                if (node.call_params) {
                    for (const p of node.call_params) {
                        args.push(await this.evaluate(p));
                    }
                }

                if (funcName === '__FMT') {
                    // Formatting: value, width, precision
                    const val = args[0];
                    const width = args[1] || 0;
                    const precision = args[2];

                    if (typeof val === 'number') {
                        if (precision !== undefined && precision !== null) {
                            // Fixed point
                            let strKey = val.toFixed(precision);
                            // Pad left
                            if (width > strKey.length) {
                                strKey = " ".repeat(width - strKey.length) + strKey;
                            }
                            return strKey;
                        } else {
                            // Just width padding
                            let strKey = val.toString();
                            if (width > strKey.length) {
                                strKey = " ".repeat(width - strKey.length) + strKey;
                            }
                            return strKey;
                        }
                    }
                    return val;
                }
                // Other builtins
                if (funcName === 'ROUND') return Math.round(args[0]);
                if (funcName === 'TRUNC') return Math.trunc(args[0]);
                if (funcName === 'ABS') return Math.abs(args[0]);
                if (funcName === 'SQR') return args[0] * args[0];
                if (funcName === 'SQRT') return Math.sqrt(args[0]);

                return 0; // Unknown function

            case 'expr_binop':
                const left = await this.evaluate(node.left);
                const right = await this.evaluate(node.right);
                switch (node.op.toLowerCase()) {
                    case 'plus': return left + right; // Might concat strings too
                    case 'minus': return left - right;
                    case 'star': return left * right;
                    case 'slash': return left / right;
                    case 'div': return Math.floor(left / right);
                    case 'mod': return left % right;
                    case 'and': return left && right;
                    case 'or': return left || right;
                    case 'eq': return left == right; // loose equality
                    case 'neq': return left != right;
                    case 'gt': return left > right;
                    case 'lt': return left < right;
                    case 'geq': return left >= right;
                    case 'leq': return left <= right;
                }
                break;
            case 'expr_unop':
                const expr = await this.evaluate(node.expr);
                if (node.op === 'not') return !expr;
                if (node.op === 'minus') return -expr;
                break;
        }
        return 0; // Fallback
    }

    recordTrace(node) {
        // Debounce: If we just recorded this line, maybe don't record again immediately for same node type?
        // But loops need re-recording.
        // We record everything. The game UI usually handles replay.

        // Capture variables (shallow copy)
        const currentVars = {};
        for (const k in this.variables) {
            if (Object.prototype.hasOwnProperty.call(this.variables, k)) {
                currentVars[k] = this.variables[k];
            }
        }

        this.traceSteps.push({
            lineIndex: node.lineno,
            text: "", // Optional, game might use it
            logs: [...this.currentLogs], // Copy logs
            variables: currentVars
        });

        this.lastLineRecorded = node.lineno;
    }

    recordError(error) {
        // Capture variables
        const currentVars = {};
        for (const k in this.variables) {
            if (Object.prototype.hasOwnProperty.call(this.variables, k)) {
                currentVars[k] = this.variables[k];
            }
        }

        this.traceSteps.push({
            lineIndex: this.lastLineRecorded,
            text: "ERROR",
            logs: [...this.currentLogs],
            variables: currentVars,
            error: error.message
        });
    }

}
